openapi: 3.0.3
info:
  title: Til7701 API
  version: 1.0.0

servers:
  - url: https://til7701.de/api/v1

paths:
  /info/request:
    $ref: './paths/info-request.yaml'

components:
  schemas:
    requestInfo:
      $ref: './components/schemas/requestInfo.yaml'
