name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install -y lftp

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate OpenAPI Docs
        run: |
          cd openapi
          ./validate.sh

      - name: Build OpenAPI Docs
        run: |
          cd openapi
          ./bundle.sh

      - name: Build HTML Templates
        run: |
          docker run --rm --name pandoc \
          -w /app \
          -v "$(pwd)":/app \
          pandoc/core:3.7-alpine sh -c "ls -al && scripts/convert.sh"

      - name: Build CSS
        run: scripts/build-css.sh

      - name: Create Build Info
        run: scripts/build-info.sh

      - name: Deploy to Server
        run: |
          lftp -u "${{ secrets.FTP_USER }}","${{ secrets.FTP_SECRET }}" "${{ secrets.FTP_HOST }}" <<EOF
          mirror --reverse --verbose --delete --parallel=2 site /
          quit
          EOF
